disabled_rules: # rule identifiers to exclude from running
    - cyclomatic_complexity
    - weak_delegate
    - trailing_whitespace
    - syntactic_sugar
    - identifier_name
    - line_length
    - force_cast


excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Carthage
    - Pods

    
#line_length:
#    - 600
#    - 700
    
type_body_length:
    warning: 500
    error: 700
    
identifier_name:
  allowed_symbols: "_"

reporter: "xcode"
